[package]
name = "ccp_nimbus"
version = "0.3.0"
authors = ["Prateesh Goyal <prateesh@mit.edu>"]
edition = "2018"

[dependencies]
anyhow = "1"
num-complex="0.2"
portus = "0.5"
rand="0.5"
rustfft="3"
tracing="0.1"
structopt = "0.2"
